//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryData.DbData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ability
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Effect { get; set; }
        public Nullable<int> Tier { get; set; }
        public string Cost { get; set; }
    }
}
