//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryData.DbData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advancement
    {
        public int Id { get; set; }
        public Nullable<int> CharacterID { get; set; }
        public Nullable<int> Tier { get; set; }
        public Nullable<bool> Capabilities { get; set; }
        public Nullable<bool> Perfection { get; set; }
        public Nullable<bool> Effort { get; set; }
        public Nullable<bool> Skills { get; set; }
        public Nullable<bool> Other { get; set; }
    }
}
