//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryData.DbData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Descriptor { get; set; }
        public string Type { get; set; }
        public string Focus { get; set; }
        public Nullable<int> Tier { get; set; }
        public Nullable<int> Effort { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Background { get; set; }
        public Nullable<int> MightMax { get; set; }
        public Nullable<int> SpeedMax { get; set; }
        public Nullable<int> IntellectMax { get; set; }
        public Nullable<int> MightEdge { get; set; }
        public Nullable<int> SpeedEdge { get; set; }
        public Nullable<int> IntellectEdge { get; set; }
        public Nullable<int> CypherLimit { get; set; }
        public Nullable<int> Armor { get; set; }
        public Nullable<int> MightCurrent { get; set; }
        public Nullable<int> SpeedCurrent { get; set; }
        public Nullable<int> IntellectCurrent { get; set; }
        public string Inabilities { get; set; }
    }
}
