//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryData.DbData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterAbility
    {
        public int Id { get; set; }
        public Nullable<int> CharacterID { get; set; }
        public Nullable<int> AbilityID { get; set; }
        public string CharacterName { get; set; }
        public string AbilityName { get; set; }
    }
}
